### ISSUE TITLE
crawling nested anchors are not found

### ISSUE THREAD

**Issue by j-mendez** [madeindjs/spider#2]
Currently, if you run the test against a website that has nested anchor tags the crawler will not pick up the links. It seems that we need to retry the selector to get all the links. You can use www.drake.com as an example to test against.

Great package btw.

**Comment by berkes** [comment]
I'm not entirely sure what you are referring to, so please correct me if I understand you wrong. 

[Nested Link tags are illegal in HTML](https://www.w3.org/TR/html401/struct/links.html#h-12.2.2):
> an A element must not contain any other A elements.

I did find that `spider` crawls pages with `#achors` just fine, and follows them; which may be a bit strange, since most often `me.html`, `me.html#foo` and `me.html#bar` are the same resource: they have the same content. Fragments are typically not sent along with the request either, so maybe you meant that `spider` is wrong there?

**Comment by j-mendez** [comment]
@berkes you make a very good point. I need to verify the html to see if this is what is happening.

**Comment by j-mendez** [comment]
Issue has been fixed. Closing.
